### PR TITLE
fix windows color output

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by romanornr** [comment]
What does it fix?
For Windows perhaps?

**Comment by ghost** [comment]
https://github.com/gookit/color has better support and works for Windows 👍

**Comment by romanornr** [comment]
utACK

**Comment by romanornr** [comment]
Oh some merge conflicts. I'll check later

**Comment by ghost** [comment]
well it works until it doesn't. let's hope for recovery.

**Comment by romanornr** [comment]
I was proud of it in 2020

I discovered severe flaws in my logic & using statistics since they're option straddles with much more

IV, gamma, theta which ftx introduced later. In the end, I never got the chance to introduce V2

But FTX seems dead for now. Totally forgot to reply on conflicting merg. I had temporarily a different job during the pandemic to keep myself from not drowning.

There's another repo I worked on "autodealer" (didn't come up with a good name actually)

**Pull request closed without merging**
